version: '3.9'
services:
  mongo:
    image: mongo:6
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db
  redis:
    image: redis:7
    ports:
      - '6379:6379'
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - mongo
      - redis
    environment:
      - PORT=4000
      - MONGO_URI=mongodb://mongo:27017/moonlightlogger
      - REDIS_URL=redis://redis:6379
      - NODE_ENV=production
    ports:
      - '4000:4000'
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - '5173:5173'
    environment:
      - NODE_ENV=production
volumes:
  mongo_data:

